### ISSUE TITLE
Corrigir a adequação da página index.html quando menor que 1100px

### ISSUE THREAD

**Issue by htmribeiro** [htmribeiro/project-proffys-nlw2#1]
## page-landing.css
```css
@media (max-width: 699px) {    /* Alterar para 1100px */
    :root {
        font-size: 40%; /* modificar as medidas rem */
    }    
```
